### ISSUE TITLE
Debug panic for tabs inside single line comment

### ISSUE THREAD

**Issue by ry** [dsherret/dprint#142]
This file: https://github.com/denoland/deno/blob/2115b38fef654c2d7c5998f40967fcfe39d7c515/cli/js/web/streams/writable-internals.ts

```
> RUST_BACKTRACE=1 ./target/debug/deno fmt cli/js/web/streams/writable-internals.ts
thread 'main' panicked at 'Found a tab in the string. Before sending the string to the printer it needs to be broken up and the tab sent as a PrintItem::Tab. //       // 	Assert: state is "writable" or "erroring".', /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-core-0.11.0/src/printer.rs:356:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: std::thread::local::fast::Key<T>::try_initialize
  13: dprint_core::printer::Printer<TString,TInfo,TCondition>::validate_string
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-plugin-typescript-0.8.0/<::std::macros::panic macros>:9
  14: dprint_core::printer::Printer<TString,TInfo,TCondition>::handle_string
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-core-0.11.0/src/printer.rs:337
  15: dprint_core::printer::Printer<TString,TInfo,TCondition>::handle_print_node
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-core-0.11.0/src/printer.rs:133
  16: dprint_core::printer::Printer<TString,TInfo,TCondition>::print
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-core-0.11.0/src/printer.rs:77
  17: dprint_core::get_write_items::get_write_items
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-core-0.11.0/src/get_write_items.rs:22
  18: dprint_core::print::print
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-core-0.11.0/src/print.rs:20
  19: dprint_plugin_typescript::format_text::format_text::{{closure}}
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-plugin-typescript-0.8.0/src/format_text.rs:45
  20: scoped_tls::ScopedKey<T>::set
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  21: dprint_plugin_typescript::format_text::format_text
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-plugin-typescript-0.8.0/src/format_text.rs:35
  22: deno::fmt::format_source_files::{{closure}}
             at cli/fmt.rs:107
  23: std::panicking::try::do_call
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panicking.rs:292
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  25: std::panicking::try
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panicking.rs:270
  26: std::panic::catch_unwind
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panic.rs:394
  27: deno::fmt::format_source_files
             at cli/fmt.rs:106
  28: deno::fmt::format
             at cli/fmt.rs:170
  29: deno::main::{{closure}}
             at cli/lib.rs:447
  30: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/future.rs:43
  31: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/future/future.rs:119
  32: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/basic_scheduler.rs:138
  33: tokio::runtime::Runtime::block_on::{{closure}}
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:413
  34: tokio::runtime::context::enter
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/context.rs:72
  35: tokio::runtime::handle::Handle::enter
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/handle.rs:34
  36: tokio::runtime::Runtime::block_on
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:410
  37: deno::tokio_util::run_basic
             at cli/tokio_util.rs:18
  38: deno::main
             at cli/lib.rs:486
  39: deno::main
             at cli/main.rs:4
  40: std::rt::lang_start::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  41: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  42: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  43: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  44: std::panicking::try
             at src/libstd/panicking.rs:270
  45: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  46: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  47: std::rt::lang_start
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  48: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
dprint panic cli/js/web/streams/writable-internals.ts
```

**Comment by dsherret** [comment]
Minimal reproduction (tab character inside):

```ts
//	t
```
